<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Txfio.Tests.Support</RootNamespace>
    <AssemblyName>Txfio.TestSupport</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit" Version="2.9.3" />
  </ItemGroup>

</Project>
